name: Node CI

on: [push]

jobs:
  build:

    # have this run on ubuntu-latest, macOS-latest && windows-latest?
    runs-on: macOS-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, build, and test
      run: |
        yarn install
        cd packages/adapter-node
        yarn build
        cd ../sblendid
        yarn build
        yarn test
      env:
        CI: true
